### ISSUE TITLE
Wrong code position with Typescript

### ISSUE THREAD

**Issue by Ninerian** [futurestudio/hapi-dev-errors#14]
Hi, thanks for hapi-dev-errors. I use it in a project which is written in Typescript. Now I noticed, that the line position in the error message are not matching the code. 

I use ts-node to run the dev server, with source-maps activated. When I use the debugger, the position matches correctly.

Do you have some tips how to solve this?

**Comment by marcuspoehls** [comment]
@Ninerian Hey Daniel, I probably can't help here. I'm not using Typescript and don't have an idea of where to look for this issue.

Would you please share a screenshot of the issue? It's not related to Typescript and we can fix it in the JS codebase

**Comment by Ninerian** [comment]
I fixed it by following the instructions here: https://github.com/whitecolor/ts-node-dev/issues/44

**Comment by marcuspoehls** [comment]
Nice! Thank you for sharing your solution :+1:
